language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

branches:
  only:
    - travis-shipit-pm2

addons:
  ssh_known_hosts: poker4.fun

before_script:
  - openssl aes-256-cbc -K $encrypted_ce2eceff5e82_key -iv $encrypted_ce2eceff5e82_iv
    -in deploy_key.enc -out ~\/poker_server_deploy_key -d

script:
  # - npm run test

after_success:
  - shipit production deploy
