dist: trusty
sudo: false

language: node_js
node_js:
  - 6
cache: yarn

addons:
  ssh_known_hosts: poker4.fun

before_install:
  - yarn global add shipit-cli

before_script:
  - openssl aes-256-cbc -K $encrypted_ce2eceff5e82_key -iv $encrypted_ce2eceff5e82_iv
    -in deploy_key.enc -out ~/.ssh/deploy_key -d
  - chmod 600 ~/.ssh/deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/deploy_key

script:
  - npm run test

deploy:
  - provider: script
    skip_cleanup: true
    script: shipit production deploy
